### ISSUE TITLE
Improvements to the Service sublanding pages

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_services#221] opened 2023-07-13 15:18 UTC
> Hey @willguv !
> 
> We're discussing service sub-landing pages in the Tech Drop-in. 
> 
> @andybroomfield is extending / altering the service sub-landing page with some new paragraph types. This caused PHP warnings which we are working around. 
> 
> This now pushes the question of "Do we want to reassess the Service Sub-Landing page structure / IA?"
> 
> maybe we could discuss this at some point int he Backlog group.
> 

_Originally posted by @finnlewis in https://github.com/localgovdrupal/localgov_services/issues/218#issuecomment-1634373776_

**Comment by finnlewis** [comment] 2023-07-18 13:35
Duplicate of #204 , closing.

**Closed as completed by finnlewis** 2023-07-18 13:35 UTC
